# Chapter 5: The 🤗 Datasets Library

🤗 Datasets provides loading scripts to handle the loading of local and remote datasets. It supports several common data formats, such as:

| Data format         | Loading script | Example                                           |
|---------------------|----------------|---------------------------------------------------|
| CSV & TSV           | csv            | `load_dataset("csv", data_files="my_file.csv")`  |
| Text files          | text           | `load_dataset("text", data_files="my_file.txt")` |
| JSON & JSON Lines   | json           | `load_dataset("json", data_files="my_file.jsonl")`|
| Pickled DataFrames  | pandas         | `load_dataset("pandas", data_files="my_dataframe.pkl")`|


The data_files argument of the **load_dataset()** function is quite flexible and can be either a single file path, a list of file paths, or a dictionary that maps split names to file paths. You can also glob files that match a specified pattern according to the rules used by the Unix shell (e.g., you can glob all the JSON files in a directory as a single split by setting data_files="*.json"). See the 🤗 Datasets documentation for more details.

In [ ]:
%pip install transformers
%pip install datasets
%pip install wget
%pip install gzip

## Loading datasets

### Loading a local dataset

For this example we’ll use the SQuAD-it dataset, which is a large-scale dataset for question answering in Italian.

#### Download and decompress files

1. The training and test splits are hosted on GitHub, so we can download them with a simple wget command. This will download two compressed files called SQuAD_it-train.json.gz and SQuAD_it-test.json.gz:
`%wget https://github.com/crux82/squad-it/raw/master/SQuAD_it-train.json.gz`
`%wget https://github.com/crux82/squad-it/raw/master/SQuAD_it-test.json.gz`

2. We can decompress the files with the Linux gzip command:
`%gzip -dkv SQuAD_it-*.json.gz`

Note that the line magic function doesn't work on this notebook. We use the non magic function

In [32]:
import wget, gzip, glob, os

wget.download('https://github.com/crux82/squad-it/raw/master/SQuAD_it-train.json.gz')
wget.download('https://github.com/crux82/squad-it/raw/master/SQuAD_it-test.json.gz')

file_list = glob.glob("SQuAD_it-*.json.gz")
for compressed_file in file_list:
    decompressed_file = compressed_file[:-3] # Create a decompressed file name by removing the ".gz" extension
    with gzip.open(compressed_file, 'rb') as gzipped_file, open(decompressed_file, 'wb') as output_file:
        output_file.write(gzipped_file.read())
    os.remove(compressed_file) # Clean up: remove the zip file

#### Load with Load_dataset() function

To load a JSON file with the **load_dataset()** function, we just need to know if we’re dealing with ordinary JSON (similar to a nested dictionary) or JSON Lines (line-separated JSON). Like many question answering datasets, SQuAD-it uses the nested format, with all the text stored in a data field. 

1. This means we can load the dataset by specifying the field argument as follows.
2. Called the variable shows us the number of rows and the column names associated with the training set. By default, loading local files creates a DatasetDict object with a train split. 
3. We can view one of the examples by indexing into the train split as follows:

In [3]:
from datasets import load_dataset

squad_it_dataset = load_dataset("json", data_files="SQuAD_it-train.json", field="data")

c:\Users\vguigon\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Downloading data files: 100%|██████████| 1/1 [00:00<?, ?it/s]
Extracting data files: 100%|██████████| 1/1 [00:00<00:00, 501.59it/s]
Generating train split: 442 examples [00:00, 754.24 examples/s]

In [4]:
squad_it_dataset

DatasetDict({
    train: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 442
    })
})

In [5]:
squad_it_dataset["train"][0]

{'title': 'Terremoto del Sichuan del 2008',
 'paragraphs': [{'context': "Il terremoto del Sichuan del 2008 o il terremoto del Gran Sichuan, misurato a 8.0 Ms e 7.9 Mw, e si è verificato alle 02:28:01 PM China Standard Time all' epicentro (06:28:01 UTC) il 12 maggio nella provincia del Sichuan, ha ucciso 69.197 persone e lasciato 18.222 dispersi.",
   'qas': [{'answers': [{'answer_start': 29, 'text': '2008'}],
     'id': '56cdca7862d2951400fa6826',
     'question': 'In quale anno si è verificato il terremoto nel Sichuan?'},
    {'answers': [{'answer_start': 232, 'text': '69.197'}],
     'id': '56cdca7862d2951400fa6828',
     'question': 'Quante persone sono state uccise come risultato?'},
    {'answers': [{'answer_start': 29, 'text': '2008'}],
     'id': '56d4f9902ccc5a1400d833c0',
     'question': 'Quale anno ha avuto luogo il terremoto del Sichuan?'},
    {'answers': [{'answer_start': 78, 'text': '8.0 Ms e 7.9 Mw'}],
     'id': '56d4f9902ccc5a1400d833c1',
     'question': 'Che cosa ha fatto la misura di sisma?'},
    {'answers': [{'answer_start': 183, 'text': '12 maggio'}],
     'id': '56d4f9902ccc5a1400d833c2',
     'question': 'Che giorno si è verificato il terremoto?'},
    {'answers': [{'answer_start': 118,
       'text': '02:28:01 PM China Standard Time'}],
     'id': '56d4f9902ccc5a1400d833c3',
     'question': 'Che ora del giorno è accaduto il terremoto?'},
    {'answers': [{'answer_start': 232, 'text': '69.197'}],
     'id': '56d4f9902ccc5a1400d833c4',
     'question': 'Quante persone sono morte?'}]},
  {'context': 'E\' noto anche come terremoto di Wenchuan (Cinese:????; pinyin: Wènchu? n dà dìzhèn; letteralmente:"Grande terremoto di Wenchuan"), dopo l\' ubicazione dell\' epicentro del terremoto, Wenchuan County, Sichuan. L\' epicentro era di 80 chilometri (50 miglia) ad ovest nord-ovest di Chengdu, capoluogo di provincia, con una profondità focale di 19 km (12 miglia). Il terremoto ha colpito anche i paesi vicini e lontani da Pechino e Shanghai-1.500 km (930 mi) e 1.700 km (1.060 mi) di distanza, dove gli edifici adibiti a uffici hanno oscillato con il tremore. Forti scosse di assestamento, un po\' superiori alla magnitudo 6, hanno continuato a colpire l\' area anche mesi dopo il sisma principale, causando nuove vittime e danni.',
   'qas': [{'answers': [{'answer_start': 415, 'text': 'Pechino e Shanghai'}],
     'id': '56cdcb2c62d2951400fa6830',
     'question': 'Quali città lontane in altri paesi potrebbero sentire il terremoto?'},
    {'answers': [{'answer_start': 338, 'text': '19 km'}],
     'id': '56cdcb2c62d2951400fa6833',
     'question': 'Qual è stata la profondità focale del terremoto?'},
    {'answers': [{'answer_start': 659, 'text': 'mesi dopo'}],
     'id': '56cdcb2c62d2951400fa6834',
     'question': 'Quanto tempo dopo il terremoto si sono sentite le scosse di assestamento?'},
    {'answers': [{'answer_start': 181, 'text': 'Wenchuan County, Sichuan'}],
     'id': '56d4fb6f2ccc5a1400d833d5',
     'question': "Dov' era l' epicentro del terremoto?"},
    {'answers': [{'answer_start': 227, 'text': '80 chilometri'}],
     'id': '56d4fb6f2ccc5a1400d833d6',
     'question': 'Quanto lontano era da Chengdu?'},
    {'answers': [{'answer_start': 338, 'text': '19 km'}],
     'id': '56d4fb6f2ccc5a1400d833d7',
     'question': 'Qual era la profondità focale del sisma?'}]},
  {'context': "I dati ufficiali (al 21 luglio 2008 ore 12:00 CST) hanno dichiarato che 69.197 sono stati confermati morti, di cui 68.636 nella provincia del Sichuan e 374.176 feriti, di cui 18.222 scomparsi. Il terremoto ha lasciato circa 4,8 milioni di senzatetto, anche se il numero potrebbe raggiungere gli 11 milioni. Circa 15 milioni di persone vivevano nell' area colpita. E' stato il terremoto più mortale per colpire la Cina dopo il terremoto di Tangshan 1976, che ha ucciso almeno 240.000 persone, e il più forte del paese dal terremoto di Chayu 1950, che ha registrato a 8,5 sulla scala di magnitudo Richter. E' il 21° terremoto più morto di tutti i tempi. Il 6 novembre 2008, il governo centrale ha annunciato che avrebbe speso 1 trilione di RMB (circa 146,5 miliardi di dollari USA) nei prossimi tre anni per ricostruire le aree devastate dal terremoto, come parte del programma cinese di stimolo economico.",
   'qas': [{'answers': [{'answer_start': 72, 'text': '69.197'}],
     'id': '56cdcbb762d2951400fa683a',
     'question': 'Quante persone sono state confermate morte?'},
    {'answers': [{'answer_start': 115, 'text': '68.636'}],
     'id': '56cdcbb762d2951400fa683b',
     'question': 'Quanti morti sono stati confermati solo nella provincia del Sichuan?'},
    {'answers': [{'answer_start': 224, 'text': '4,8 milioni'}],
     'id': '56cdcbb762d2951400fa683c',
     'question': 'Quante persone sono rimaste senza tetto a causa del terremoto?'},
    {'answers': [{'answer_start': 313, 'text': '15 milioni'}],
     'id': '56cdcbb762d2951400fa683d',
     'question': 'Quante persone hanno vissuto nella zona colpita?'},
    {'answers': [{'answer_start': 724, 'text': '1 trilione di RMB'}],
     'id': '56cdcbb762d2951400fa683e',
     'question': 'Quanto denaro è stato destinato alla ricostruzione di aree devastate?'},
    {'answers': [{'answer_start': 115, 'text': '68.636'}],
     'id': '56d4fca52ccc5a1400d833de',
     'question': 'Quante persone sono morte nella provincia del Sichuan?'},
    {'answers': [{'answer_start': 152, 'text': '374.176'}],
     'id': '56d4fca52ccc5a1400d833df',
     'question': 'Quanti sono stati feriti nel Sichuan?'},
    {'answers': [{'answer_start': 175, 'text': '18.222'}],
     'id': '56d4fca52ccc5a1400d833e0',
     'question': 'Quante persone sono elencate come scomparse?'},
    {'answers': [{'answer_start': 224, 'text': '4,8 milioni'}],
     'id': '56d4fca52ccc5a1400d833e1',
     'question': 'Quante persone sono senzatetto a causa del terremoto?'},
    {'answers': [{'answer_start': 295, 'text': '11 milioni'}],
     'id': '56d4fca52ccc5a1400d833e2',
     'question': 'Quanto potrebbe arrivare il numero dei senzatetto?'}]},
  {'context': "Il terremoto ha avuto una magnitudine di 8,0 Ms e 7,9 Mw. L' epicentro è stato in Wenchuan County, Ngawa Tibetano e Prefettura Autonoma di Qiang, 80 km ad ovest / nord-ovest del capoluogo di provincia di Chengdu, con il suo tremore principale che si verifica alle 14:28:01.42 China Standard Time (06:28:01.42 UTC), il 12 maggio 2008 della durata di circa 2 minuti, nel terremoto quasi l' 80% degli edifici sono stati distrutti.",
   'qas': [{'answers': [{'answer_start': 355, 'text': '2 minuti'}],
     'id': '56cdcc5562d2951400fa6847',
     'question': 'Quanto tempo è durato il terremoto?'},
    {'answers': [{'answer_start': 388, 'text': '80%'}],
     'id': '56cdcc5562d2951400fa6848',
     'question': 'Quale percentuale di edifici è stata distrutta?'},
    {'answers': [{'answer_start': 41, 'text': '8,0 Ms e 7,9 Mw'}],
     'id': '56d4fe332ccc5a1400d833e8',
     'question': 'Qual era la magnitudo del terremoto?'},
    {'answers': [{'answer_start': 355, 'text': '2 minuti'}],
     'id': '56d4fe332ccc5a1400d833eb',
     'question': 'Quanto tempo è durato il tremore principale?'},
    {'answers': [{'answer_start': 379, 'text': "quasi l' 80%"}],
     'id': '56d4fe332ccc5a1400d833ec',
     'question': 'Quale percentuale di edifici è stata distrutta durante il sisma?'}]},
  {'context': "Secondo uno studio della China Earthquake Administration (CEA), il terremoto si è verificato lungo la faglia Longmenshan, una struttura di spinta lungo il confine della piastra Indo-Australiana e placca eurasiatica. Le attività sismiche si sono concentrate sulla sua frattura media (nota come frattura Yingxiu-Beichuan). La rottura è durata quasi 120 sec, con la maggior parte dell' energia rilasciata nei primi 80 sec. Partendo da Wenchuan, la rottura si propagò ad una velocità media di 3,1 chilometri al secondo 49° verso nord-est, rompendosi per un totale di circa 300 km. Lo spostamento massimo ammontava a 9 metri. Il fuoco era più profondo di 10 km.",
   'qas': [{'answers': [{'answer_start': 347, 'text': '120 sec'}],
     'id': '56cdccd962d2951400fa6850',
     'question': 'Quanto tempo ha durato la rottura?'},
    {'answers': [{'answer_start': 650, 'text': '10 km'}],
     'id': '56cdccd962d2951400fa6852',
     'question': 'Quanto è stato profondo il centro del terremoto?'},
    {'answers': [{'answer_start': 293, 'text': 'frattura Yingxiu-Beichuan'}],
     'id': '56d5005d2ccc5a1400d833f4',
     'question': 'Su quale frattura ha messo a fuoco il terremoto?'},
    {'answers': [{'answer_start': 612, 'text': '9 metri'}],
     'id': '56d5005d2ccc5a1400d833f6',
     'question': 'Qual è stato lo sfollamento più causato dal terremoto?'}]},
  {'context': 'Yazhou Zhoukan, con sede in Malesia, ha condotto un\' intervista con l\' ex ricercatore presso il China Seismological Bureau Geng Qingguo (??), in cui Geng ha sostenuto che un rapporto scritto riservato è stato inviato all\' Ufficio sismologico di Stato il 30 aprile 2008, avvertendo circa il possibile verificarsi di un terremoto significativo nella regione della prefettura di Ngawa del Sichuan intorno all\' 8 maggio, con una gamma di 10 giorni prima o dopo il terremoto. Il Geng, pur riconoscendo che la predizione del terremoto era ampiamente considerata problematica dalla comunità scientifica, credeva che "più grande è il terremoto, più facile è prevedere". Geng aveva a lungo tentato di stabilire una correlazione tra il verificarsi di siccità e terremoti; Premier Zhou Enlai ha riferito che ha preso interesse nel lavoro di Geng. La teoria di correlazione siccità-terra terremoto di Geng è stata pubblicata per la prima volta nel 1972, e ha detto di aver pronosticato con successo i terremoti di Haicheng 1975 e 1976 Tangshan. Lo stesso articolo di Yazhou Zhoukan ha sottolineato le difficoltà intrinseche associate alla previsione dei terremoti.',
   'qas': [{'answers': [{'answer_start': 936, 'text': '1972'}],
     'id': '56cdce0b62d2951400fa685b',
     'question': 'Quando è stata rilasciata la teoria di correlazione siccità-terra terremoto di Geng?'},
    {'answers': [{'answer_start': 394, 'text': "intorno all' 8 maggio"}],
     'id': '56d67a8d1c8504140094714f',
     'question': 'Qual era il tempo previsto per il terremoto?'},
    {'answers': [{'answer_start': 741, 'text': 'siccità'}],
     'id': '56d67a8d1c85041400947150',
     'question': 'Che cosa ha cercato Geng a lungo di stabilire come rapporto con i terremoti?'}]},
  {'context': 'In uno studio dell\' USGS (United States Geological Survey) i modelli preliminari di rottura del terremoto hanno indicato uno spostamento fino a 9 metri lungo un guasto lungo circa 240 km di lunghezza e 20 km di profondità. Il terremoto ha generato deformazioni della superficie superiori a 3 metri e ha aumentato lo stress (e la probabilità che si verifichino eventi futuri) alle estremità nord-orientale e sud-occidentale del guasto. Il 20 maggio, il sismologo dell\' USGS Tom Parsons ha avvertito che c\' è "alto rischio" di una grave scossa di assestamento M>7 nelle prossime settimane o mesi.',
   'qas': [{'answers': [{'answer_start': 137, 'text': 'fino a 9 metri'}],
     'id': '56cdcebe62d2951400fa6862',
     'question': 'Quanto è stato grande lo spostamento?'},
    {'answers': [{'answer_start': 473, 'text': 'Tom Parsons'}],
     'id': '56cdcebe62d2951400fa6866',
     'question': "Chi ha prima messo in guardia da possibili attività sismiche nell' area?"},
    {'answers': [{'answer_start': 144, 'text': '9 metri'}],
     'id': '56d5027a9d1b871400ae05e1',
     'question': "Che cosa ha mostrato il Geological Survey degli Stati Uniti come l' entità dello spostamento?"},
    {'answers': [{'answer_start': 202, 'text': '20 km di profondità'}],
     'id': '56d5027a9d1b871400ae05e3',
     'question': 'Quanto è profondo il guasto?'},
    {'answers': [{'answer_start': 508, 'text': 'alto rischio'}],
     'id': '56d5027a9d1b871400ae05e5',
     'question': 'Che cosa ha considerato Tom Parsons come il fattore di rischio per forti terremoti futuri?'}]},
  {'context': 'Sismologo giapponese Yuji Yagi Yuji Yagi presso l\' Università di Tsukuba ha detto che il terremoto si è verificato in due fasi:"Il 155 miglia Longmenshan Fault tore in due sezioni, il primo uno strappo di circa sette metri, seguita da un secondo che ha tosato quattro metri". I suoi dati hanno anche mostrato che il terremoto è durato circa due minuti e ha rilasciato 30 volte l\' energia del grande terremoto di Hanshin del 1995 in Giappone, che ha ucciso oltre 6.000 persone. Egli ha sottolineato che la scarsità dell\' epicentro e la densità di popolazione hanno notevolmente aumentato la gravità del terremoto. Teruyuki Kato, un sismologo dell\' Università di Tokyo, ha detto che le onde sismiche del terremoto hanno percorso una lunga distanza senza perdere il loro potere a causa della fermezza del terreno nella Cina centrale.',
   'qas': [{'answers': [{'answer_start': 115, 'text': 'in due fasi'}],
     'id': '56d504539d1b871400ae05eb',
     'question': 'Come ha fatto Yuji Yagi a dire che il terremoto è successo?'},
    {'answers': [{'answer_start': 142, 'text': 'Longmenshan Fault'}],
     'id': '56d504539d1b871400ae05ec',
     'question': 'Che errore si è verificato in due luoghi?'},
    {'answers': [{'answer_start': 368, 'text': '30 volte'}],
     'id': '56d504539d1b871400ae05ee',
     'question': 'Quanta più energia di quella prodotta dal terremoto del 1995 in Giappone?'},
    {'answers': [{'answer_start': 789, 'text': 'fermezza del terreno'}],
     'id': '56d504539d1b871400ae05ef',
     'question': 'Perché le onde sismiche hanno viaggiato finora?'}]},
  {'context': 'Tra 64 e 104 scosse di assestamento importanti, di magnitudo compresa tra 4,0 e 6,1, sono state registrate entro 72 ore dal sisma principale. Secondo i conteggi ufficiali cinesi,"alle ore 12:00 CST, 6 novembre 2008 c\' erano state 42.719 scariche post-shock totali, di cui 246 variavano da 4,0 SM a 4,9 SM, 34 da 5,0 MS a 5,9 MS, e 8 da 6,0 Ms a 6,4 MS; l\' urto post-shock più forte misurato 6,4 MS." L\' ultima scossa post-shock superiore a M6 si è verificato il 5 agosto.',
   'qas': [{'answers': [{'answer_start': 0, 'text': 'Tra 64 e 104'}],
     'id': '56cdd08862d2951400fa6894',
     'question': 'Quante sono state le scosse di assestamento?'},
    {'answers': [{'answer_start': 107,
       'text': 'entro 72 ore dal sisma principale'}],
     'id': '56cdd08862d2951400fa6896',
     'question': 'Quando sono state registrate le scosse di assestamento?'},
    {'answers': [{'answer_start': 0, 'text': 'Tra 64 e 104'}],
     'id': '56d505f99d1b871400ae05f5',
     'question': 'Quante sono state le scosse di assestamento entro 72 ore?'},
    {'answers': [{'answer_start': 230, 'text': '42.719'}],
     'id': '56d505f99d1b871400ae05f6',
     'question': 'Che cosa dicono i cinesi è il numero totale di shock dopo il terremoto?'},
    {'answers': [{'answer_start': 272, 'text': '246'}],
     'id': '56d505f99d1b871400ae05f8',
     'question': 'In quale data si sono verificate le scosse di assestamento più recenti superiori a 6 SM?'}]},
  {'context': '(Il terremoto della sig. ra 6.1 del 30 agosto 2008 nel Sichuan meridionale non faceva parte di questa serie perché è stato causato da una diversa colpa.',
   'qas': [{'answers': [{'answer_start': 55, 'text': 'Sichuan meridionale'}],
     'id': '56cdd10962d2951400fa68a0',
     'question': 'Dove si è verificato il terremoto?'},
    {'answers': [{'answer_start': 55, 'text': 'Sichuan meridionale'}],
     'id': '56cdd10962d2951400fa68a2',
     'question': "Dov' era il terremoto del 30 agosto 2008?"},
    {'answers': [{'answer_start': 20, 'text': 'sig'}],
     'id': '56d507269d1b871400ae05ff',
     'question': 'Qual era la grandezza del terremoto del Sichuan meridionale?'}]},
  {'context': 'La mappa dell\' intensità sismica pubblicata dal CEA dopo aver rilevato 500.000 km2 dell\' area colpita mostra una liedu massima di XI sulla scala di intensità sismica cinese (CSIS), descritta come "molto distruttiva" sulla scala macrosismica europea (EMS) da cui il CSIS ha tratto riferimento. (USGS, utilizzando la scala di intensità Mercalli modificata (CC), collocava anche l\' intensità massima a XI,"molto disastrosa". Due strisce sud-ovest-nord-est di liedu XI sono centrate intorno a Yingxiu, Wenchuan (la città più vicina all\' epicentro del terremoto principale) e Beichuan (la città ripetutamente colpita da forti scosse di assestamento tra cui una che registra MS 6.1 il 1 agosto 2008), entrambe nella provincia del Sichuan, occupando un totale di 2.419 km2. La zona Yingxiu liedu-XI è lunga circa 66 km e larga 20 km lungo Wenchuan-Dujiangyan-Pengzhou; la zona Beichuan liedu-XI è lunga circa 82 km e larga 15 km lungo An County-Beichuan-Pingwu. L\' area con liedu X (comparabile a X su EMS,"distruttivo" e X su MM,"disastroso") ha una superficie di 3.144 km2.',
   'qas': [{'answers': [{'answer_start': 48, 'text': 'CEA'}],
     'id': '56cdd21562d2951400fa68b0',
     'question': "Chi ha pubblicato la mappa dell' intensità dei terremoti?"},
    {'answers': [{'answer_start': 130, 'text': 'XI'}],
     'id': '56cdd21562d2951400fa68b2',
     'question': 'A quale intensità è stata scalata?'},
    {'answers': [{'answer_start': 489, 'text': 'Yingxiu, Wenchuan'}],
     'id': '56d5098a9d1b871400ae0609',
     'question': "Quale città era più vicina all' epicentro principale?"}]},
  {'context': "Il sistema Longmen Shan Fault System si trova al confine orientale dell' altopiano tibetano e contiene diversi difetti. Questo terremoto ha rotto almeno due strutture imbricate in Longmen Shan Fault System, vale a dire il Fault Beichuan e il Guanxian-Anxian Fault. Nell' area epicentrale, lo slittamento medio in Fault Beichuan era di circa 3,5 metri (11 ft) verticale, di 3,5 metri (11 ft) orizzontale parallelo al guasto, e di 4,8 metri (16 ft) orizzontale-pendicolare al guasto. Nell' area di circa 30 chilometri (19 miglia) a nord-est dell' epicentro, lo scivolamento superficiale su Beichuan Fault è stato quasi esclusivamente dextral strike-slip fino a circa 3 metri, mentre lo scivolamento medio in Guanxian-Anxian Fault è stato di circa 2 metri verticali (6 ft 7 in) e 2,3 metri (7 ft 7 in) orizzontali. il confine orientale dell' altopiano tibetano.",
   'qas': [{'answers': [{'answer_start': 665, 'text': '3 metri'}],
     'id': '56cdd4d762d2951400fa68cd',
     'question': 'Quanto è stato grande lo slip 30 km a nord-est del guasto?'},
    {'answers': [{'answer_start': 745, 'text': '2 metri'}],
     'id': '56cdd4d762d2951400fa68ce',
     'question': 'Qual è stato lo slittamento verticale media sul Guanxian-Anxian errore?'},
    {'answers': [{'answer_start': 777, 'text': '2,3 metri'}],
     'id': '56cdd4d762d2951400fa68cf',
     'question': 'Che cosa è stato lo slittamento orizzontale media sul Guanxian-Anxian errore?'},
    {'answers': [{'answer_start': 73, 'text': 'altopiano tibetano'}],
     'id': '56cdd4d762d2951400fa68d0',
     'question': 'Dove si trova il guasto dello shan Longmen?'},
    {'answers': [{'answer_start': 3,
       'text': 'sistema Longmen Shan Fault System'}],
     'id': '56d516439d1b871400ae0611',
     'question': 'Dove sono i guasti Beichuan e Guanxian-Ansia?'},
    {'answers': [{'answer_start': 341, 'text': '3,5 metri'}],
     'id': '56d516439d1b871400ae0612',
     'question': 'Qual è stato lo slittamento verticale medio nel difetto di Beichaun?'},
    {'answers': [{'answer_start': 341, 'text': '3,5 metri'}],
     'id': '56d516439d1b871400ae0613',
     'question': "Qual è stato lo slittamento orizzontale nel Fault Beichuan all' epicentro?"},
    {'answers': [{'answer_start': 429, 'text': '4,8 metri'}],
     'id': '56d516439d1b871400ae0614',
     'question': 'Qual è stato lo slittamento orizzontale perpendicolare al guasto?'}]},

#### Load with Dataset.map() function

While this worked for the training set, what we really want is to include both the train and test splits in a single DatasetDict object so we can apply **Dataset.map()** functions across both splits at once. 

To do this, we can provide a dictionary to the data_files argument that maps each split name to a file associated with that split:

In [6]:
data_files = {"train": "SQuAD_it-train.json", "test": "SQuAD_it-test.json"}
squad_it_dataset = load_dataset("json", data_files=data_files, field="data")
squad_it_dataset

Downloading data files: 100%|██████████| 2/2 [00:00<?, ?it/s]
Extracting data files: 100%|██████████| 2/2 [00:00<00:00, 1003.06it/s]
Generating train split: 442 examples [00:00, 722.10 examples/s]
Generating test split: 48 examples [00:00, 521.39 examples/s]

DatasetDict({
    train: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 442
    })
    test: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 48
    })
})

#### Load and Decompress with Load_dataset() function

The data_files argument of the load_dataset() function is quite flexible and can be either a single file path, a list of file paths, or a dictionary that maps split names to file paths. You can also glob files that match a specified pattern according to the rules used by the Unix shell (e.g., you can glob all the JSON files in a directory as a single split by setting data_files="*.json"). See the 🤗 Datasets documentation for more details.

In [7]:
data_files = {"train": "SQuAD_it-train.json.gz", "test": "SQuAD_it-test.json.gz"}
squad_it_dataset = load_dataset("json", data_files=data_files, field="data")

Downloading data files: 100%|██████████| 2/2 [00:00<?, ?it/s]
Extracting data files: 100%|██████████| 2/2 [00:00<00:00, 597.22it/s]
Generating train split: 442 examples [00:00, 750.28 examples/s]
Generating test split: 48 examples [00:00, 496.39 examples/s]

### Loading a remote dataset

If you’re working as a data scientist or coder in a company, there’s a good chance the datasets you want to analyze are stored on some remote server. Fortunately, loading remote files is just as simple as loading local ones! Instead of providing a path to local files, we point the data_files argument of load_dataset() to one or more URLs where the remote files are stored. For example, for the SQuAD-it dataset hosted on GitHub, we can just point data_files to the SQuAD_it-*.json.gz URLs as follows.

This returns the same DatasetDict object obtained above, but saves us the step of manually downloading and decompressing the SQuAD_it-*.json.gz files.

In [8]:
url = "https://github.com/crux82/squad-it/raw/master/"
data_files = {
    "train": url + "SQuAD_it-train.json.gz",
    "test": url + "SQuAD_it-test.json.gz",
}
squad_it_dataset = load_dataset("json", data_files=data_files, field="data")

## Slice and Dice (Cleaning) a dataset

Similar to Pandas, 🤗 Datasets provides several functions to manipulate the contents of Dataset and DatasetDict objects. 

1. For this example we’ll use the Drug Review Dataset that’s hosted on the UC Irvine Machine Learning Repository, which contains patient reviews on various drugs, along with the condition being treated and a 10-star rating of the patient’s satisfaction.

2. Since TSV is just a variant of CSV that uses tabs instead of commas as the separator, we can load these files by using the csv loading script and specifying the delimiter argument in the **load_dataset()** function.

In [9]:
import wget, os
from zipfile import ZipFile 

wget.download("https://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip")

current_directory = os.getcwd()
with ZipFile("drugsCom_raw.zip", 'r') as zip_ref:
    zip_ref.extractall(current_directory) # unzipped file in the root folder

os.remove("drugsCom_raw.zip") # Clean up: remove the zip file

In [10]:
from datasets import load_dataset

data_files = {"train": "drugsComTrain_raw.tsv", "test": "drugsComTest_raw.tsv"}
# \t is the tab character in Python
drug_dataset = load_dataset("csv", data_files=data_files, delimiter="\t")

Downloading data files: 100%|██████████| 2/2 [00:00<?, ?it/s]
Extracting data files: 100%|██████████| 2/2 [00:00<00:00, 990.04it/s]
Generating train split: 161297 examples [00:01, 155497.38 examples/s]
Generating test split: 53766 examples [00:00, 149223.25 examples/s]

### Peak at the data

A good practice when doing any sort of data analysis is to grab a small random sample to get a quick feel for the type of data you’re working with. In 🤗 Datasets, we can create a random sample by chaining the **Dataset.shuffle()** and **Dataset.select()** functions together, as below.

Note that we’ve fixed the seed in Dataset.shuffle() for reproducibility purposes. Dataset.select() expects an iterable of indices, so we’ve passed range(1000) to grab the first 1,000 examples from the shuffled dataset. From this sample we can already see a few quirks in our dataset:
* The Unnamed: 0 column looks suspiciously like an anonymized ID for each patient.
* The condition column includes a mix of uppercase and lowercase labels.
* The reviews are of varying length and contain a mix of Python line separators (\r\n) as well as HTML character codes like &\#039;.

Let’s see how we can use 🤗 Datasets to deal with each of these issues.

In [11]:
drug_sample = drug_dataset["train"].shuffle(seed=42).select(range(1000))
# Peek at the first few examples
drug_sample[:3]

{'Unnamed: 0': [87571, 178045, 80482],
 'drugName': ['Naproxen', 'Duloxetine', 'Mobic'],
 'condition': ['Gout, Acute', 'ibromyalgia', 'Inflammatory Conditions'],
 'review': ['"like the previous person mention, I&#039;m a strong believer of aleve, it works faster for my gout than the prescription meds I take. No more going to the doctor for refills.....Aleve works!"',
  '"I have taken Cymbalta for about a year and a half for fibromyalgia pain. It is great\r\nas a pain reducer and an anti-depressant, however, the side effects outweighed \r\nany benefit I got from it. I had trouble with restlessness, being tired constantly,\r\ndizziness, dry mouth, numbness and tingling in my feet, and horrible sweating. I am\r\nbeing weaned off of it now. Went from 60 mg to 30mg and now to 15 mg. I will be\r\noff completely in about a week. The fibro pain is coming back, but I would rather deal with it than the side effects."',
  '"I have been taking Mobic for over a year with no side effects other than an elevated blood pressure.  I had severe knee and ankle pain which completely went away after taking Mobic.  I attempted to stop the medication however pain returned after a few days."'],
 'rating': [9.0, 3.0, 10.0],
 'date': ['September 2, 2015', 'November 7, 2011', 'June 5, 2013'],
 'usefulCount': [36, 13, 128]}

### Clean suspicious columns

1. To test the patient ID hypothesis for the Unnamed: 0 column, we can use the **Dataset.unique()** function to verify that the number of IDs matches the number of rows in each split.

2. Our hypothesis confirmed, let’s clean up the dataset a bit by renaming the Unnamed: 0 column to something a bit more interpretable. We can use the **DatasetDict.rename_column()** function to rename the column across both splits in one go.

3. We drop the rows that are *None* using **Dataset.filter()**, which works in a similar way to Dataset.map() and expects a function that receives a single example of the dataset. We can do this in one line using a *lambda function* (i.e., small functions that can be defined without explicitly naming them)

4. Let's normalize all the condition labels using **Dataset.map()**. As we did with tokenization in Chapter 3, we can define a simple function that can be applied across all the rows of each split in drug_dataset.

In [12]:
for split in drug_dataset.keys():
    assert len(drug_dataset[split]) == len(drug_dataset[split].unique("Unnamed: 0"))

In [13]:
drug_dataset = drug_dataset.rename_column(
    original_column_name="Unnamed: 0", new_column_name="patient_id"
)
drug_dataset

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 161297
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 53766
    })
})

In [14]:
drug_dataset = drug_dataset.filter(lambda x: x["condition"] is not None)

Filter: 100%|██████████| 161297/161297 [00:01<00:00, 132085.85 examples/s]
Filter: 100%|██████████| 53766/53766 [00:00<00:00, 132549.02 examples/s]

In [15]:
def lowercase_condition(example):
    return {"condition": example["condition"].lower()}
    
drug_dataset = drug_dataset.map(lowercase_condition)
# Check that lowercasing worked
drug_dataset["train"]["condition"][:3]

Map: 100%|██████████| 160398/160398 [00:18<00:00, 8805.53 examples/s]
Map: 100%|██████████| 53471/53471 [00:06<00:00, 8856.31 examples/s]

['left ventricular dysfunction', 'adhd', 'birth control']

### Create new columns

Whenever you’re dealing with customer reviews, a good practice is to check the number of words in each review. A review might be just a single word like “Great!” or a full-blown essay with thousands of words, and depending on the use case you’ll need to handle these extremes differently. To compute the number of words in each review, we’ll use a rough heuristic based on splitting each text by whitespace.


1. Let’s define a simple function that counts the number of words in each review.

2. Now we add the corresponding column.
Unlike our **lowercase_condition()** function, **compute_review_length()** returns a dictionary whose key does not correspond to one of the column names in the dataset. In this case, when **compute_review_length()** is passed to **Dataset.map()**, it will be applied to all the rows in the dataset to create a new *review_length column*.

3. We can review the column.
As expected, we can see a review_length column has been added to our training set. We can sort this new column with Dataset.sort() to see what the extreme values look like.

4. Let’s use the **Dataset.filter()** function to remove reviews that contain fewer than 30 words. Similarly to what we did with the condition column, we can filter out the very short reviews by requiring that the reviews have a length above this threshold.

5. The last thing we need to deal with is the presence of HTML character codes in our reviews. We can use Python’s html module to unescape these characters. We’ll use **Dataset.map()** to unescape all the HTML characters in our corpus.


🙋 An alternative way to add new columns to a dataset is with the Dataset.add_column() function. This allows you to provide the column as a Python list or NumPy array and can be handy in situations where Dataset.map() is not well suited for your analysis.

In [17]:
def compute_review_length(example):
    return {"review_length": len(example["review"].split())}

In [18]:
drug_dataset = drug_dataset.map(compute_review_length)
# Inspect the first training example
drug_dataset["train"][0]

Map: 100%|██████████| 160398/160398 [00:13<00:00, 11553.21 examples/s]
Map: 100%|██████████| 53471/53471 [00:04<00:00, 11578.19 examples/s]

{'patient_id': 206461,
 'drugName': 'Valsartan',
 'condition': 'left ventricular dysfunction',
 'review': '"It has no side effect, I take it in combination of Bystolic 5 Mg and Fish Oil"',
 'rating': 9.0,
 'date': 'May 20, 2012',
 'usefulCount': 27,
 'review_length': 17}

In [19]:
drug_dataset["train"].sort("review_length")[:3]

{'patient_id': [111469, 13653, 53602],
 'drugName': ['Ledipasvir / sofosbuvir',
  'Amphetamine / dextroamphetamine',
  'Alesse'],
 'condition': ['hepatitis c', 'adhd', 'birth control'],
 'review': ['"Headache"', '"Great"', '"Awesome"'],
 'rating': [10.0, 10.0, 10.0],
 'date': ['February 3, 2015', 'October 20, 2009', 'November 23, 2015'],
 'usefulCount': [41, 3, 0],
 'review_length': [1, 1, 1]}

In [20]:
drug_dataset = drug_dataset.filter(lambda x: x["review_length"] > 30)
print(drug_dataset.num_rows)

Filter: 100%|██████████| 160398/160398 [00:01<00:00, 122623.07 examples/s]
Filter: 100%|██████████| 53471/53471 [00:00<00:00, 123526.79 examples/s]

{'train': 138514, 'test': 46108}

In [21]:
import html

drug_dataset = drug_dataset.map(lambda x: {"review": html.unescape(x["review"])})

Map: 100%|██████████| 138514/138514 [00:17<00:00, 7773.12 examples/s]
Map: 100%|██████████| 46108/46108 [00:05<00:00, 7711.56 examples/s]

### Batch processes with the Map() method

The **Dataset.map()** method takes a batched argument that, if set to True, causes it to send a batch of examples to the map function at once (the batch size is configurable but defaults to 1,000). For instance, the previous map function that unescaped all the HTML took a bit of time to run (you can read the time taken from the progress bars). We can speed this up by processing several elements at the same time using a list comprehension.

When you specify batched=True the function receives a dictionary with the fields of the dataset, but each value is now a list of values, and not just a single value. The return value of Dataset.map() should be the same: a dictionary with the fields we want to update or add to our dataset, and a list of values. For example, here is another way to unescape all HTML characters, but using batched=True.

If you’re running this code in a notebook, you’ll see that this command executes way faster than the previous one.
This is because list comprehensions are usually faster than executing the same code in a for loop, and we also gain some performance by accessing lots of elements at the same time instead of one by one.

In [22]:
new_drug_dataset = drug_dataset.map(
    lambda x: {"review": [html.unescape(o) for o in x["review"]]}, batched=True
)

Map: 100%|██████████| 138514/138514 [00:00<00:00, 337894.76 examples/s]
Map: 100%|██████████| 46108/46108 [00:00<00:00, 350894.55 examples/s]

#### Fast tokenizing with batch from map() method

Using **Dataset.map()** with batched=True will be essential to unlock the speed of the “fast” tokenizers that we’ll encounter in Chapter 6, which can quickly tokenize big lists of texts. 

1. For instance, to tokenize all the drug reviews with a fast tokenizer, we could use a function like what follows.

2. We can pass one or several examples to the tokenizer, so we can use this function with or without batched=True. Let’s take this opportunity to compare the performance of the different options. In a notebook, you can time a one-line instruction by adding %time before the line of code you wish to measure.

Here are the results we obtained with and without batching, with a fast and a slow tokenizer:
Options	        Fast tokenizer	Slow tokenizer
batched=True	10.8s	        4min41s
batched=False	59.2s	        5min3s

That’s the main reason why fast tokenizers are the default when using AutoTokenizer (and why they are called “fast”). They’re able to achieve such a speedup because behind the scenes the tokenization code is executed in Rust, which is a language that makes it easy to parallelize code execution.

In [23]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

def tokenize_function(examples):
    return tokenizer(examples["review"], truncation=True)

In [24]:
%time tokenized_dataset = drug_dataset.map(tokenize_function, batched=True)

Map: 100%|██████████| 138514/138514 [00:17<00:00, 8084.94 examples/s]
Map: 100%|██████████| 46108/46108 [00:05<00:00, 8037.84 examples/s]

CPU times: total: 1min 5s
Wall time: 22.9 s

#### Parallelization from map() method

Parallelization is also the reason for the nearly 6x speedup the fast tokenizer achieves with batching: you can’t parallelize a single tokenization operation, but when you want to tokenize lots of texts at the same time you can just split the execution across several processes, each responsible for its own texts.

Dataset.map() also has some parallelization capabilities of its own. Since they are not backed by Rust, they won’t let a slow tokenizer catch up with a fast one, but they can still be helpful (especially if you’re using a tokenizer that doesn’t have a fast version). To enable multiprocessing, use the num_proc argument and specify the number of processes to use in your call to Dataset.map().

However, I only got 1 proc on this computer, therefore the param is set to 1.

Notes from HuggingFace: 
For values of num_proc other than 8, our tests showed that it was faster to use batched=True without that option. In general, we don’t recommend using Python multiprocessing for fast tokenizers with batched=True.

In [26]:
from transformers import AutoTokenizer

slow_tokenizer = AutoTokenizer.from_pretrained("bert-base-cased", use_fast=False)

def slow_tokenize_function(examples):
    return slow_tokenizer(examples["review"], truncation=True)

In [ ]:
%time tokenized_dataset = drug_dataset.map(slow_tokenize_function, batched=True, num_proc=1)

#### Change nb elems in the dataset with map() method

All of this functionality condensed into a single method is already pretty amazing, but there’s more! With Dataset.map() and batched=True you can change the number of elements in your dataset. This is super useful in many situations where you want to create several training features from one example, and we will need to do this as part of the preprocessing for several of the NLP tasks we’ll undertake in Chapter 7.

💡 In machine learning, an example is usually defined as the set of features that we feed to the model. In some contexts, these features will be the set of columns in a Dataset, but in others (like here and for question answering), multiple features can be extracted from a single example and belong to a single column.


Let’s have a look at how it works! 

1. Here we will tokenize our examples and truncate them to a maximum length of 128, but we will ask the tokenizer to return all the chunks of the texts instead of just the first one. This can be done with return_overflowing_tokens=True.

2. Our first example in the training set became two features because it was tokenized to more than the maximum number of tokens we specified: the first one of length 128 and the second one of length 49.

3. If we do it for all elements of the dataset, there is a mismatch in the lengths of one of the columns, one being of length 1,463 and the other of length 1,000. 
The problem is that we’re trying to mix two different datasets of different sizes: the drug_dataset columns will have a certain number of examples (the 1,000 in our error), but the tokenized_dataset we are building will have more (the 1,463 in the error message; it is more than 1,000 because we are tokenizing long reviews into more than one example by using return_overflowing_tokens=True). That doesn’t work for a Dataset, so we need to either remove the columns from the old dataset or make them the same size as they are in the new dataset. 

4. We can make them the same size as they are in the new dataset with the remove_columns argument.

5. Let's check that our new dataset has many more elements than the original dataset by comparing the lengths.

6. We can also deal with the mismatched length problem by making the old columns the same size as the new ones. To do this, we will need the overflow_to_sample_mapping field the tokenizer returns when we set return_overflowing_tokens=True. It gives us a mapping from a new feature index to the index of the sample it originated from. Using this, we can associate each key present in our original dataset with a list of values of the right size by repeating the values of each example as many times as it generates new features.

In [33]:
def tokenize_and_split(examples):
    return tokenizer(
        examples["review"],
        truncation=True,
        max_length=128,
        return_overflowing_tokens=True,
    )

In [34]:
result = tokenize_and_split(drug_dataset["train"][0])
[len(inp) for inp in result["input_ids"]]

[128, 49]

In [35]:
tokenized_dataset = drug_dataset.map(tokenize_and_split, batched=True)

Map:   0%|          | 0/138514 [00:00<?, ? examples/s]

ArrowInvalid: Column 8 named input_ids expected length 1000 but got length 1463

In [36]:
tokenized_dataset = drug_dataset.map(
    tokenize_and_split, batched=True, remove_columns=drug_dataset["train"].column_names
)

Map: 100%|██████████| 138514/138514 [00:46<00:00, 2985.58 examples/s]
Map: 100%|██████████| 46108/46108 [00:15<00:00, 3033.32 examples/s]

In [37]:
len(tokenized_dataset["train"]), len(drug_dataset["train"])

(206772, 138514)

In [39]:
def tokenize_and_split(examples):
    result = tokenizer(
        examples["review"],
        truncation=True,
        max_length=128,
        return_overflowing_tokens=True,
    )
    # Extract mapping between new and old indices
    sample_map = result.pop("overflow_to_sample_mapping")
    for key, values in examples.items():
        result[key] = [values[i] for i in sample_map]
    return result

tokenized_dataset = drug_dataset.map(tokenize_and_split, batched=True)
tokenized_dataset

Map: 100%|██████████| 138514/138514 [00:46<00:00, 2951.87 examples/s]
Map: 100%|██████████| 46108/46108 [00:15<00:00, 2951.21 examples/s]

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 206772
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 68876
    })
})

### From 'Datasets' to 'Dataframes' and back

To enable the conversion between various third-party libraries, 🤗 Datasets provides a Dataset.set_format() function. This function only changes the output format of the dataset, so you can easily switch to another format without affecting the underlying data format, which is Apache Arrow. The formatting is done in place. 

1. To demonstrate, let’s convert our dataset to Pandas

2. Now when we access elements of the dataset we get a pandas.DataFrame instead of a dictionary.

3. Let’s create a pandas.DataFrame for the whole training set by selecting all the elements of drug_dataset["train"].

🚨 Under the hood, Dataset.set_format() changes the return format for the dataset’s __getitem__() dunder method. This means that when we want to create a new object like train_df from a Dataset in the "pandas" format, we need to slice the whole dataset to obtain a pandas.DataFrame. You can verify for yourself that the type of drug_dataset["train"] is Dataset, irrespective of the output format.

4. From here we can use all the Pandas functionality that we want. For example, we can do fancy chaining to compute the class distribution among the condition entries.

5. And once we’re done with our Pandas analysis, we can always create a new Dataset object by using the Dataset.from_pandas() function.

6. Finally, reset the output format of drug_dataset from "pandas" to "arrow".

In [40]:
drug_dataset.set_format("pandas")

In [41]:
drug_dataset["train"][:3]

,patient_id,drugName,condition,review,rating,date,usefulCount,review_length
0,95260,Guanfacine,adhd,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192,141
1,92703,Lybrel,birth control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17,134
2,138000,Ortho Evra,birth control,"""This is my first time using any form of birth...",8.0,"November 3, 2015",10,89

In [42]:
train_df = drug_dataset["train"][:]

In [43]:
frequencies = (
    train_df["condition"]
    .value_counts()
    .to_frame()
    .reset_index()
    .rename(columns={"index": "condition", "condition": "frequency"})
)
frequencies.head()

       frequency  count
0  birth control  27655
1     depression   8023
2           acne   5209
3        anxiety   4991
4           pain   4744

In [44]:
from datasets import Dataset

freq_dataset = Dataset.from_pandas(frequencies)
freq_dataset

Dataset({
    features: ['frequency', 'count'],
    num_rows: 819
})

In [45]:
drug_dataset.reset_format()

### Creating a validation set

Although we have a test set we could use for evaluation, it’s a good practice to leave the test set untouched and create a separate validation set during development. Once you are happy with the performance of your models on the validation set, you can do a final sanity check on the test set. This process helps mitigate the risk that you’ll overfit to the test set and deploy a model that fails on real-world data.

🤗 Datasets provides a Dataset.train_test_split() function that is based on the famous functionality from scikit-learn. Let’s use it to split our training set into train and validation splits (we set the seed argument for reproducibility).

In [46]:
drug_dataset_clean = drug_dataset["train"].train_test_split(train_size=0.8, seed=42)
# Rename the default "test" split to "validation"
drug_dataset_clean["validation"] = drug_dataset_clean.pop("test")
# Add the "test" set to our `DatasetDict`
drug_dataset_clean["test"] = drug_dataset["test"]
drug_dataset_clean

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 110811
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 27703
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46108
    })
})

### Saving a dataset

Although 🤗 Datasets will cache every downloaded dataset and the operations performed on it, there are times when you’ll want to save a dataset to disk (e.g., in case the cache gets deleted). As shown in the table below, 🤗 Datasets provides three main functions to save your dataset in different formats:

Data format	    Function
Arrow	        Dataset.save_to_disk()
CSV	            Dataset.to_csv()
JSON	        Dataset.to_json()

#### Save in Arrow format

1. Let’s save our cleaned dataset in the Arrow format:
```
drug-reviews/
├── dataset_dict.json
├── test
│   ├── dataset.arrow
│   ├── dataset_info.json
│   └── state.json
├── train
│   ├── dataset.arrow
│   ├── dataset_info.json
│   ├── indices.arrow
│   └── state.json
└── validation
    ├── dataset.arrow
    ├── dataset_info.json
    ├── indices.arrow
    └── state.json
```

Each split is associated with its own dataset.arrow table, and some metadata in dataset_info.json and state.json. You can think of the Arrow format as a fancy table of columns and rows that is optimized for building high-performance applications that process and transport large datasets.

2. Once the dataset is saved, we can load it by using the load_from_disk() function

In [47]:
drug_dataset_clean.save_to_disk("drug-reviews")

Saving the dataset (1/1 shards): 100%|██████████| 110811/110811 [00:01<00:00, 109835.36 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 27703/27703 [00:00<00:00, 108916.67 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 46108/46108 [00:00<00:00, 1489972.41 examples/s]

In [48]:
from datasets import load_from_disk

drug_dataset_reloaded = load_from_disk("drug-reviews")
drug_dataset_reloaded

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 110811
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 27703
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46108
    })
})

#### Save in CSV and JSON formats

For the CSV and JSON formats, we have to store each split as a separate file. One way to do this is by iterating over the keys and values in the DatasetDict object.

1. Let's save in JSON
2. Let's load the JSON

In [49]:
for split, dataset in drug_dataset_clean.items():
    dataset.to_json(f"drug-reviews-{split}.jsonl")

Creating json from Arrow format: 100%|██████████| 111/111 [00:01<00:00, 72.83ba/s]
Creating json from Arrow format: 100%|██████████| 28/28 [00:00<00:00, 78.01ba/s]
Creating json from Arrow format: 100%|██████████| 47/47 [00:00<00:00, 151.43ba/s]

In [50]:
data_files = {
    "train": "drug-reviews-train.jsonl",
    "validation": "drug-reviews-validation.jsonl",
    "test": "drug-reviews-test.jsonl",
}
drug_dataset_reloaded = load_dataset("json", data_files=data_files)

Downloading data files: 100%|██████████| 3/3 [00:00<00:00, 3003.80it/s]
Extracting data files: 100%|██████████| 3/3 [00:00<00:00, 992.97it/s]
Generating train split: 110811 examples [00:00, 547511.70 examples/s]
Generating validation split: 27703 examples [00:00, 590627.83 examples/s]
Generating test split: 46108 examples [00:00, 436412.51 examples/s]

## Handling Big Data

🤗 Datasets has been designed to overcome Big Data loading limitations. It frees you from memory management problems by treating datasets as memory-mapped files, and from hard drive limits by streaming the entries in a corpus.
In this section we’ll explore these features of 🤗 Datasets with a huge 825 GB corpus known as the Pile.

### The pile

The Pile is an English text corpus that was created by EleutherAI for training large-scale language models. It includes a diverse range of datasets, spanning scientific articles, GitHub code repositories, and filtered web text. The training corpus is available in 14 GB chunks, and you can also download several of the individual components. Let’s start by taking a look at the PubMed Abstracts dataset, which is a corpus of abstracts from 15 million biomedical publications on PubMed. 

1. The dataset is in JSON Lines format and is compressed using the zstandard library, so first we need to install that.

2. Then we can load the dataset using the method for remote files

3. We inspect the contents of the first example

4. We can measure memory usage in Python is with the psutil library
Note: the *rss* attribute refers to the resident set size, which is the fraction of memory that a process occupies in RAM. This measurement also includes the memory used by the Python interpreter and the libraries we’ve loaded, so the actual amount of memory used to load the dataset is a bit smaller.

5. Inspect size on disk

In [52]:
%pip install zstandard
%pip install psutil

Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: zstandard in c:\users\vguigon\appdata\local\programs\python\python311\lib\site-packages (0.22.0)

[notice] A new release of pip is available: 23.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: psutil in c:\users\vguigon\appdata\roaming\python\python311\site-packages (5.9.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from datasets import load_dataset

# This takes a few minutes to run, so go grab a tea or coffee while you wait :)
data_files = "https://the-eye.eu/public/AI/pile_preliminary_components/PUBMED_title_abstracts_2019_baseline.jsonl.zst"
pubmed_dataset = load_dataset("json", data_files=data_files, split="train")
pubmed_dataset

In [ ]:
pubmed_dataset[0]

In [ ]:
import psutil

# Process.memory_info is expressed in bytes, so convert to megabytes
print(f"RAM used: {psutil.Process().memory_info().rss / (1024 * 1024):.2f} MB")

In [ ]:
print(f"Number of files in dataset : {pubmed_dataset.dataset_size}")
size_gb = pubmed_dataset.dataset_size / (1024**3)
print(f"Dataset size (cache file) : {size_gb:.2f} GB")

### Memory mapping

🤗 Datasets solve memory management problem by treating each dataset as a memory-mapped file, which provides a mapping between RAM and filesystem storage that allows the library to access and operate on elements of the dataset without needing to fully load it into memory.

Memory-mapped files can also be shared across multiple processes, which enables methods like Dataset.map() to be parallelized without needing to move or copy the dataset. Under the hood, these capabilities are all realized by the Apache Arrow memory format and pyarrow library, which make the data loading and processing lightning fast. (For more details about Apache Arrow and comparisons to Pandas, check out Dejan Simic’s blog post.) 

1. Let's perform a speed test:


However, in some cases, datasets are too large to be stored on laptos. 🤗 Datasets provides a streaming feature that allows us to download and access elements on the fly, without needing to download the whole dataset. Let’s take a look at how this works.

In [ ]:
import timeit

code_snippet = """batch_size = 1000

for idx in range(0, len(pubmed_dataset), batch_size):
    _ = pubmed_dataset[idx:idx + batch_size]
"""

time = timeit.timeit(stmt=code_snippet, number=1, globals=globals())
print(
    f"Iterated over {len(pubmed_dataset)} examples (about {size_gb:.1f} GB) in "
    f"{time:.1f}s, i.e. {size_gb/time:.3f} GB/s"
)

### Streaming datasets

To enable dataset streaming you just need to pass the streaming=True argument to the load_dataset() function. 

1. For example, let’s load the PubMed Abstracts dataset again, but in streaming mode.

2. Instead of the familiar Dataset that we’ve encountered elsewhere in this chapter, the object returned with streaming=True is an IterableDataset. As the name suggests, to access the elements of an IterableDataset we need to iterate over it. We can access the first element of our streamed dataset.

3. The elements from a streamed dataset can be processed on the fly using IterableDataset.map(), which is useful during training if you need to tokenize the inputs.
💡 To speed up tokenization with streaming you can pass batched=True, as we saw in the last section. It will process the examples batch by batch; the default batch size is 1,000 and can be specified with the batch_size argument.

4. You can also shuffle a streamed dataset using IterableDataset.shuffle(), but unlike Dataset.shuffle() this only shuffles the elements in a predefined buffer_size.

In this example, we selected a random example from the first 10,000 examples in the buffer. Once an example is accessed, its spot in the buffer is filled with the next example in the corpus (i.e., the 10,001st example in the case above). 

5. You can also select elements from a streamed dataset using the IterableDataset.take() and IterableDataset.skip() functions, which act in a similar way to Dataset.select(). For example, to select the first 5 examples in the PubMed Abstracts dataset we can do the following

6. Similarly, you can use the IterableDataset.skip() function to create training and validation splits from a shuffled dataset

In [54]:
data_files = "https://the-eye.eu/public/AI/pile_preliminary_components/PUBMED_title_abstracts_2019_baseline.jsonl.zst"

pubmed_dataset_streamed = load_dataset(
    "json", data_files=data_files, split="train", streaming=True
)

FileNotFoundError: Unable to find 'https://the-eye.eu/public/AI/pile_preliminary_components/PUBMED_title_abstracts_2019_baseline.jsonl.zst'

In [ ]:
next(iter(pubmed_dataset_streamed))

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
tokenized_dataset = pubmed_dataset_streamed.map(lambda x: tokenizer(x["text"]))
next(iter(tokenized_dataset))

In [ ]:
shuffled_dataset = pubmed_dataset_streamed.shuffle(buffer_size=10_000, seed=42)
next(iter(shuffled_dataset))

In [ ]:
dataset_head = pubmed_dataset_streamed.take(5)
list(dataset_head)

In [ ]:
# Skip the first 1,000 examples and include the rest in the training set
train_dataset = shuffled_dataset.skip(1000)
# Take the first 1,000 examples for the validation set
validation_dataset = shuffled_dataset.take(1000)

#### Combining multiple datasets together

Let’s round out our exploration of dataset streaming with a common application: combining multiple datasets together to create a single corpus. 🤗 Datasets provides an interleave_datasets() function that converts a list of IterableDataset objects into a single IterableDataset, where the elements of the new dataset are obtained by alternating among the source examples. This function is especially useful when you’re trying to combine large datasets, so as an example let’s stream the FreeLaw subset of the Pile, which is a 51 GB dataset of legal opinions from US courts.

1. Load a dataset
This dataset is large enough to stress the RAM of most laptops, yet we’ve been able to load and access it without breaking a sweat! 

2. Let’s now combine the examples from the FreeLaw and PubMed Abstracts datasets with the interleave_datasets() function
Here we’ve used the islice() function from Python’s itertools module to select the first two examples from the combined dataset, and we can see that they match the first examples from each of the two source datasets.

3. Finally, if you want to stream the Pile in its 825 GB entirety, you can grab all the prepared files as follows

In [ ]:
law_dataset_streamed = load_dataset(
    "json",
    data_files="https://the-eye.eu/public/AI/pile_preliminary_components/FreeLaw_Opinions.jsonl.zst",
    split="train",
    streaming=True,
)
next(iter(law_dataset_streamed))

In [ ]:
from itertools import islice
from datasets import interleave_datasets

combined_dataset = interleave_datasets([pubmed_dataset_streamed, law_dataset_streamed])
list(islice(combined_dataset, 2))

In [ ]:
base_url = "https://the-eye.eu/public/AI/pile/"
data_files = {
    "train": [base_url + "train/" + f"{idx:02d}.jsonl.zst" for idx in range(30)],
    "validation": base_url + "val.jsonl.zst",
    "test": base_url + "test.jsonl.zst",
}
pile_dataset = load_dataset("json", data_files=data_files, streaming=True)
next(iter(pile_dataset["train"]))

## Creating your own dataset

Sometimes the dataset that you need to build an NLP application doesn’t exist, so you’ll need to create it yourself. In this section we’ll show you how to create a corpus of GitHub issues, which are commonly used to track bugs or features in GitHub repositories. This corpus could be used for various purposes, including:
* Exploring how long it takes to close open issues or pull requests
* Training a multilabel classifier that can tag issues with metadata based on the issue’s description (e.g., “bug,” “enhancement,” or “question”)
* Creating a semantic search engine to find which issues match a user’s query

Here we’ll focus on creating the corpus, and in the next section we’ll tackle the semantic search application. To keep things meta, we’ll use the GitHub issues associated with a popular open source project: 🤗 Datasets! Let’s take a look at how to get the data and explore the information contained in these issues.

### Getting the data

To download all the repository’s issues, we’ll use the GitHub REST API to poll the Issues endpoint. This endpoint returns a list of JSON objects, with each object containing a large number of fields that include the title and description as well as metadata about the status of the issue and so on.

1. A convenient way to download the issues is via the requests library, which is the standard way for making HTTP requests in Python. 

2. You can make GET requests to the Issues endpoint by invoking the requests.get() function. For example, you can run a command to retrieve the first issue on the first page.

3. What we are interested in is the payload, which can be accessed in various formats like bytes, strings, or JSON. Since we know our issues are in JSON format, let’s inspect the payload as JSON

4. As described in the GitHub documentation, unauthenticated requests are limited to 60 requests per hour. Although you can increase the per_page query parameter to reduce the number of requests you make, you will still hit the rate limit on any repository that has more than a few thousand issues. So instead, you should follow GitHub’s instructions on creating a personal access token so that you can boost the rate limit to 5,000 requests per hour. Once you have your token, you can include it as part of the request header

⚠️ Do not share a notebook with your GITHUB_TOKEN pasted in it. We recommend you delete the last cell once you have executed it to avoid leaking this information accidentally. Even better, store the token in a .env file and use the python-dotenv library to load it automatically for you as an environment variable.

5. Now that we have our access token, let’s create a function that can download all the issues from a GitHub repository

6. Now when we call fetch_issues() it will download all the issues in batches to avoid exceeding GitHub’s limit on the number of requests per hour; the result will be stored in a repository_name-issues.jsonl file, where each line is a JSON object the represents an issue. Let’s use this function to grab all the issues from 🤗 Datasets

7. Once the issues are downloaded we can load them locally

In [ ]:
%pip install requests

In [5]:
import requests

url = "https://api.github.com/repos/huggingface/datasets/issues?page=1&per_page=1"
response = requests.get(url)

In [3]:
response.json()

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/6381',
  'repository_url': 'https://api.github.com/repos/huggingface/datasets',
  'labels_url': 'https://api.github.com/repos/huggingface/datasets/issues/6381/labels{/name}',
  'comments_url': 'https://api.github.com/repos/huggingface/datasets/issues/6381/comments',
  'events_url': 'https://api.github.com/repos/huggingface/datasets/issues/6381/events',
  'html_url': 'https://github.com/huggingface/datasets/pull/6381',
  'id': 1975028470,
  'node_id': 'PR_kwDODunzps5eeYty',
  'number': 6381,
  'title': 'Add my dataset',
  'user': {'login': 'keyur536',
   'id': 103646675,
   'node_id': 'U_kgDOBi2F0w',
   'avatar_url': 'https://avatars.githubusercontent.com/u/103646675?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/keyur536',
   'html_url': 'https://github.com/keyur536',
   'followers_url': 'https://api.github.com/users/keyur536/followers',
   'following_url': 'https://api.github.com/users/keyur536/following{/other_user}',
   'gists_url': 'https://api.github.com/users/keyur536/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/keyur536/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/keyur536/subscriptions',
   'organizations_url': 'https://api.github.com/users/keyur536/orgs',
   'repos_url': 'https://api.github.com/users/keyur536/repos',
   'events_url': 'https://api.github.com/users/keyur536/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/keyur536/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2023-11-02T20:59:52Z',
  'updated_at': '2023-11-02T20:59:52Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/huggingface/datasets/pulls/6381',
   'html_url': 'https://github.com/huggingface/datasets/pull/6381',
   'diff_url': 'https://github.com/huggingface/datasets/pull/6381.diff',
   'patch_url': 'https://github.com/huggingface/datasets/pull/6381.patch',
   'merged_at': None},
  'body': '## medical data\r\n\r\n**Description:**\r\nThis dataset, named "medical data," is a collection of text data from various sources, carefully curated and cleaned for use in natural language processing (NLP) tasks. It consists of a diverse range of text, including articles, books, and online content, covering topics from science to literature.\r\n\r\n**Citation:**\r\nIf applicable, please include a citation for this dataset to give credit to the original sources or contributors.\r\n\r\n**Key Features:**\r\n- Language: The text is primarily in English, but it may include content in other languages as well.\r\n- Use Cases: This dataset is suitable for text classification, language modeling, sentiment analysis, and other NLP tasks.\r\n\r\n**Usage:**\r\nTo access this dataset, use the `load_your_dataset` function provided in the `your_dataset.py` script within this repository. You can specify the dataset split you need, such as "train," "test," or "validation," to get the data for your specific task.\r\n\r\n**Contributors:**\r\n- [Keyur Chaudhari]\r\n\r\n**Contact:**\r\nIf you have any questions or need assistance regarding this dataset, please feel free to contact [keyurchaudhari536@gmail.com].\r\n\r\nPlease note that this dataset is shared under a specific license, which can be found in the [LICENSE](link to your dataset\'s license) file. Make sure to review and adhere to the terms of the license when using this dataset for your projects.\r\n',
  'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/6381/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/huggingface/datasets/issues/6381/timeline',
  'performed_via_github_app': None,
  'state_reason': None}]

In [6]:
GITHUB_TOKEN = "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"  # Copy your GitHub token here
headers = {"Authorization": f"token {GITHUB_TOKEN}"}

In [7]:
import time
import math
from pathlib import Path
import pandas as pd
from tqdm import tqdm


def fetch_issues(
    owner="huggingface",
    repo="datasets",
    num_issues=10_000,
    rate_limit=5_000,
    issues_path=Path("."),
):
    if not issues_path.is_dir():
        issues_path.mkdir(exist_ok=True)

    batch = []
    all_issues = []
    per_page = 100  # Number of issues to return per page
    num_pages = math.ceil(num_issues / per_page)
    base_url = "https://api.github.com/repos"

    for page in tqdm(range(num_pages)):
        # Query with state=all to get both open and closed issues
        query = f"issues?page={page}&per_page={per_page}&state=all"
        issues = requests.get(f"{base_url}/{owner}/{repo}/{query}", headers=headers)
        batch.extend(issues.json())

        if len(batch) > rate_limit and len(all_issues) < num_issues:
            all_issues.extend(batch)
            batch = []  # Flush batch for next time period
            print(f"Reached GitHub rate limit. Sleeping for one hour ...")
            time.sleep(60 * 60 + 1)

    all_issues.extend(batch)
    df = pd.DataFrame.from_records(all_issues)
    df.to_json(f"{issues_path}/{repo}-issues.jsonl", orient="records", lines=True)
    print(
        f"Downloaded all the issues for {repo}! Dataset stored at {issues_path}/{repo}-issues.jsonl"
    )

In [8]:
# Depending on your internet connection, this can take several minutes to run...
fetch_issues()

 50%|█████     | 50/100 [00:27<00:25,  1.95it/s]

Reached GitHub rate limit. Sleeping for one hour ...

100%|██████████| 100/100 [1:00:44<00:00, 36.45s/it]

Downloaded all the issues for datasets! Dataset stored at ./datasets-issues.jsonl

In [20]:
from datasets import load_dataset
from datasets import Dataset

try:
    issues_dataset = load_dataset("json", data_files="datasets-issues.jsonl", split="train")
    issues_dataset
except Exception:
    import pandas as pd
    df=pd.read_json("datasets-issues.jsonl", lines=True)
    df.head()

    issues_dataset = Dataset.from_pandas(df)
    issues_dataset
    sample = issues_dataset.shuffle(seed=666).select(range(3))
    sample[0]

Downloading data files:   0%|          | 0/1 [00:00<?, ?it/s]

Extracting data files:   0%|          | 0/1 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

### Cleaning up the data

> GitHub’s REST API v3 considers every pull request an issue, but not every issue is a pull request. For this reason, “Issues” endpoints may return both issues and pull requests in the response. You can identify pull requests by the pull_request key. Be aware that the id of a pull request returned from “Issues” endpoints will be an issue id.

The above snippet from GitHub’s documentation tells us that the pull_request column can be used to differentiate between issues and pull requests. 

1. Let’s look at a random sample to see what the difference is. We’ll chain Dataset.shuffle() and Dataset.select() to create a random sample and then zip the html_url and pull_request columns so we can compare the various URLs

2. re we can see that each pull request is associated with various URLs, while ordinary issues have a None entry. We can use this distinction to create a new is_pull_request column that checks whether the pull_request field is None or not

Although we could proceed to further clean up the dataset by dropping or renaming some columns, it is generally a good practice to keep the dataset as “raw” as possible at this stage so that it can be easily used in multiple applications.

In [21]:
sample = issues_dataset.shuffle(seed=666).select(range(3))

# Print out the URL and pull request entries
for url, pr in zip(sample["html_url"], sample["pull_request"]):
    print(f">> URL: {url}")
    print(f">> Pull request: {pr}\n")

>> URL: https://github.com/huggingface/datasets/issues/5786
>> Pull request: None

>> URL: https://github.com/huggingface/datasets/issues/554
>> Pull request: None

>> URL: https://github.com/huggingface/datasets/pull/6340
>> Pull request: {'diff_url': 'https://github.com/huggingface/datasets/pull/6340.diff', 'html_url': 'https://github.com/huggingface/datasets/pull/6340', 'merged_at': None, 'patch_url': 'https://github.com/huggingface/datasets/pull/6340.patch', 'url': 'https://api.github.com/repos/huggingface/datasets/pulls/6340'}

In [22]:
issues_dataset = issues_dataset.map(
    lambda x: {"is_pull_request": False if x["pull_request"] is None else True}
)

Map:   0%|          | 0/6355 [00:00<?, ? examples/s]

### Augmenting the dataset

Before we push our dataset to the Hugging Face Hub, let’s deal with one thing that’s missing from it: the comments associated with each issue and pull request. We’ll add them next with — you guessed it — the GitHub REST API!

1. The GitHub REST API provides a Comments endpoint that returns all the comments associated with an issue number. Let’s test the endpoint to see what it returns

2. We can see that the comment is stored in the body field, so let’s write a simple function that returns all the comments associated with an issue by picking out the body contents for each element in response.json()

3. This looks good, so let’s use Dataset.map() to add a new comments column to each issue in our dataset

In [23]:
issue_number = 2792
url = f"https://api.github.com/repos/huggingface/datasets/issues/{issue_number}/comments"
response = requests.get(url, headers=headers)
response.json()

[{'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/897594128',
  'html_url': 'https://github.com/huggingface/datasets/pull/2792#issuecomment-897594128',
  'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/2792',
  'id': 897594128,
  'node_id': 'IC_kwDODunzps41gDMQ',
  'user': {'login': 'bhavitvyamalik',
   'id': 19718818,
   'node_id': 'MDQ6VXNlcjE5NzE4ODE4',
   'avatar_url': 'https://avatars.githubusercontent.com/u/19718818?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/bhavitvyamalik',
   'html_url': 'https://github.com/bhavitvyamalik',
   'followers_url': 'https://api.github.com/users/bhavitvyamalik/followers',
   'following_url': 'https://api.github.com/users/bhavitvyamalik/following{/other_user}',
   'gists_url': 'https://api.github.com/users/bhavitvyamalik/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/bhavitvyamalik/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/bhavitvyamalik/subscriptions',
   'organizations_url': 'https://api.github.com/users/bhavitvyamalik/orgs',
   'repos_url': 'https://api.github.com/users/bhavitvyamalik/repos',
   'events_url': 'https://api.github.com/users/bhavitvyamalik/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/bhavitvyamalik/received_events',
   'type': 'User',
   'site_admin': False},
  'created_at': '2021-08-12T12:21:52Z',
  'updated_at': '2021-08-12T12:31:17Z',
  'author_association': 'CONTRIBUTOR',
  'body': "@albertvillanova my tests are failing here:\r\n```\r\ndataset_name = 'gooaq'\r\n\r\n    def test_load_dataset(self, dataset_name):\r\n        configs = self.dataset_tester.load_all_configs(dataset_name, is_local=True)[:1]\r\n>       self.dataset_tester.check_load_dataset(dataset_name, configs, is_local=True, use_local_dummy_data=True)\r\n\r\ntests/test_dataset_common.py:234: \r\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \r\ntests/test_dataset_common.py:187: in check_load_dataset\r\n    self.parent.assertTrue(len(dataset[split]) > 0)\r\nE   AssertionError: False is not true\r\n```\r\nWhen I try loading dataset on local machine it works fine. Any suggestions on how can I avoid this error?",
  'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/897594128/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/898644889',
  'html_url': 'https://github.com/huggingface/datasets/pull/2792#issuecomment-898644889',
  'issue_url': 'https://api.github.com/repos/huggingface/datasets/issues/2792',
  'id': 898644889,
  'node_id': 'IC_kwDODunzps41kDuZ',
  'user': {'login': 'bhavitvyamalik',
   'id': 19718818,
   'node_id': 'MDQ6VXNlcjE5NzE4ODE4',
   'avatar_url': 'https://avatars.githubusercontent.com/u/19718818?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/bhavitvyamalik',
   'html_url': 'https://github.com/bhavitvyamalik',
   'followers_url': 'https://api.github.com/users/bhavitvyamalik/followers',
   'following_url': 'https://api.github.com/users/bhavitvyamalik/following{/other_user}',
   'gists_url': 'https://api.github.com/users/bhavitvyamalik/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/bhavitvyamalik/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/bhavitvyamalik/subscriptions',
   'organizations_url': 'https://api.github.com/users/bhavitvyamalik/orgs',
   'repos_url': 'https://api.github.com/users/bhavitvyamalik/repos',
   'events_url': 'https://api.github.com/users/bhavitvyamalik/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/bhavitvyamalik/received_events',
   'type': 'User',
   'site_admin': False},
  'created_at': '2021-08-13T18:28:27Z',
  'updated_at': '2021-08-13T18:28:27Z',
  'author_association': 'CONTRIBUTOR',
  'body': 'Thanks for the help, @albertvillanova! All tests are passing now.',
  'reactions': {'url': 'https://api.github.com/repos/huggingface/datasets/issues/comments/898644889/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'performed_via_github_app': None}]

In [24]:
def get_comments(issue_number):
    url = f"https://api.github.com/repos/huggingface/datasets/issues/{issue_number}/comments"
    response = requests.get(url, headers=headers)
    return [r["body"] for r in response.json()]


# Test our function works as expected
get_comments(2792)

["@albertvillanova my tests are failing here:\r\n```\r\ndataset_name = 'gooaq'\r\n\r\n    def test_load_dataset(self, dataset_name):\r\n        configs = self.dataset_tester.load_all_configs(dataset_name, is_local=True)[:1]\r\n>       self.dataset_tester.check_load_dataset(dataset_name, configs, is_local=True, use_local_dummy_data=True)\r\n\r\ntests/test_dataset_common.py:234: \r\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \r\ntests/test_dataset_common.py:187: in check_load_dataset\r\n    self.parent.assertTrue(len(dataset[split]) > 0)\r\nE   AssertionError: False is not true\r\n```\r\nWhen I try loading dataset on local machine it works fine. Any suggestions on how can I avoid this error?",
 'Thanks for the help, @albertvillanova! All tests are passing now.']

In [25]:
# Depending on your internet connection, this can take a few minutes...
issues_with_comments_dataset = issues_dataset.map(
    lambda x: {"comments": get_comments(x["number"])}
)

Map:   0%|          | 0/6355 [00:00<?, ? examples/s]

TypeError: string indices must be integers, not 'str'

### Uploading the dataset to the HuggingFace Hub

The final step is to push our dataset to the Hub.

### Creating a dataset card

Well-documented datasets are more likely to be useful to others (including your future self!), as they provide the context to enable users to decide whether the dataset is relevant to their task and to evaluate any potential biases in or risks associated with using the dataset.

On the Hugging Face Hub, this information is stored in each dataset repository’s README.md file. There are two main steps you should take before creating this file:

1. Use the datasets-tagging application to create metadata tags in YAML format. These tags are used for a variety of search features on the Hugging Face Hub and ensure your dataset can be easily found by members of the community. Since we have created a custom dataset here, you’ll need to clone the datasets-tagging repository and run the application locally. 

2. Read the 🤗 Datasets guide on creating informative dataset cards and use it as a template.
You can create the README.md file directly on the Hub, and you can find a template dataset card in the lewtun/github-issues dataset repository. A screenshot of the filled-out dataset card is shown below.